name: health_bloom
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  lottie: ^1.0.1
  material_design_icons_flutter:
  google_fonts:
  camera:
  path_provider:
  path:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  image_picker:
  font_awesome_flutter:
  http:
  firebase_messaging:
  dio:
  charts_flutter:
  flutter_local_notifications:
  cloud_firestore:
  wiredash:
  firebase_database:
  firebase_storage:
  provider:
  pie_chart:
  google_sign_in:
  flutter_linkify:
  division:
  url_launcher:
  connectivity:
  fluttertoast:
  flutter_svg:
  percent_indicator:
  intl:
  fl_chart:
  simple_animations:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/images.png
    - images/logo.png
    - images/exercise.png
    - images/Google.png
    - images/Facebook.png
    - images/Twitter.png
    - lotties/splashimg.json
    - lotties/facebook.json
    - lotties/google.json
    - lotties/twitter.json
    - lotties/morbid-obesity.json
    - lotties/normal-result.json
    - lotties/obesity.json
    - lotties/overweight.json
    - lotties/bmiexercise.json
    - lotties/dummbells.json
    - lotties/health-app-user.json
    - lotties/virus.json
    - lotties/support.json
    - lotties/activity.json
    - lotties/presciption.json
    - lotties/settings.json
    - lotties/bmi.json
    - images/clock.png
    - images/light-2.png
    - images/light-1.png
    - images/background.png
    - assets/icons/
    - assets/images/
    - assets/images/bac.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
        - asset: assets/fonts/bebas_bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
